name: test

on:
  workflow_dispatch:
    inputs:
      cli_params:
        description: 'Run tests by cli-params'
        default: 'cy:uitest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone e2e repo
      uses: actions/checkout@v3
    
    - name: Run Test
      if: always()
      run: npm install

    - name: Add E2E
      run: |
           npm install
    
    - name: Run e2e tests
      run: |
        npm run cy:uitest
      
      
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
       ref: gh-pages
       path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
          allure_results: allure-results
          allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
